#pragma once

#define IRRIGATION_LOCAL_OUTPUT_COUNT 8U
#define IRRIGATION_MAX_ZONES IRRIGATION_LOCAL_OUTPUT_COUNT
#define IRRIGATION_MAX_PROGRAMS 4U
#define IRRIGATION_MAX_PROGRAM_STEPS 8U
#define IRRIGATION_MAX_SCHEDULES 16U
